# Generated by Django 5.2.12 on 2026-04-30 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0002_dataset_approved_at_dataset_approved_by_and_more"),
        (
            "documents",
            "0002_remove_rawdocument_documents_r_user_id_09b9e9_idx_and_more",
        ),
        ("processing", "0005_add_chunk_quality_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("document_approved", "Document Approved"),
                            ("dataset_included", "Dataset Included"),
                            ("dataset_sold", "Dataset Sold"),
                            ("annotation_submitted", "Annotation Submitted"),
                            (
                                "annotation_match_consensus",
                                "Annotation Match Consensus",
                            ),
                            (
                                "annotation_below_threshold",
                                "Annotation Below Threshold",
                            ),
                            ("expert_review_completed", "Expert Review Completed"),
                            ("conflict_resolved", "Conflict Resolved"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("points_value", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("action_type",),
            },
        ),
        migrations.CreateModel(
            name="ScoreLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("contributor", "contributor"),
                            ("annotator", "annotator"),
                            ("expert", "expert reviewer"),
                            ("buyer", "buyer"),
                            ("admin", "admin"),
                            ("unknown", "unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("document_approved", "Document Approved"),
                            ("dataset_included", "Dataset Included"),
                            ("dataset_sold", "Dataset Sold"),
                            ("annotation_submitted", "Annotation Submitted"),
                            (
                                "annotation_match_consensus",
                                "Annotation Match Consensus",
                            ),
                            (
                                "annotation_below_threshold",
                                "Annotation Below Threshold",
                            ),
                            ("expert_review_completed", "Expert Review Completed"),
                            ("conflict_resolved", "Conflict Resolved"),
                        ],
                        max_length=64,
                    ),
                ),
                ("points", models.IntegerField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_logs",
                        to="processing.chunk",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_logs",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_logs",
                        to="documents.rawdocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="score_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "default_permissions": ("add", "view"),
                "indexes": [
                    models.Index(fields=["role"], name="scoring_sco_role_a76ccb_idx"),
                    models.Index(
                        fields=["action_type"], name="scoring_sco_action__2b1f9a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="scoring_sco_created_ae8bb1_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="scoring_sco_user_id_27d7d8_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role__in", ["contributor", "annotator", "expert"])
                        ),
                        name="chk_score_log_role_scoring_only",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-total_points", "-updated_at"),
                "indexes": [
                    models.Index(
                        fields=["total_points"], name="scoring_use_total_p_0bb70f_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="scoring_use_updated_cdf8f3_idx"
                    ),
                ],
            },
        ),
    ]
