# Generated by Django 5.2.12 on 2026-05-19 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userscore",
            name="locked_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="userscore",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_points__gte", 0)),
                name="chk_user_score_total_points_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="userscore",
            constraint=models.CheckConstraint(
                condition=models.Q(("locked_points__gte", 0)),
                name="chk_user_score_locked_points_non_negative",
            ),
        ),
    ]
