# Generated by Django 5.2.12 on 2026-04-26 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_dataset_approved_at_dataset_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=8)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=12)),
                ('license_type_at_purchase', models.CharField(max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='datasets.dataset')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DatasetPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('access_status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_purchases', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_purchases', to='datasets.dataset')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_purchases', to='marketplace.orderitem')),
            ],
            options={
                'ordering': ('-purchased_at',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='marketplace_order_s_bf7444_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='marketplace_payment_71a995_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='marketplace_created_b4d26a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'created_at'], name='marketplace_buyer_i_e646ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='chk_order_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('order_status', 'completed')), models.Q(('order_status', 'completed'), _negated=True), _connector='OR'), name='chk_order_completed_requires_completed_at'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'dataset'], name='marketplace_order_i_8ed648_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'dataset'), name='uniq_order_item_order_dataset'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_at_purchase__gte', 0)), name='chk_order_item_price_at_purchase_non_negative'),
        ),
        migrations.AddIndex(
            model_name='datasetpurchase',
            index=models.Index(fields=['access_status'], name='marketplace_access__b57b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetpurchase',
            index=models.Index(fields=['buyer', 'access_status'], name='marketplace_buyer_i_188db9_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetpurchase',
            index=models.Index(fields=['dataset', 'access_status'], name='marketplace_dataset_bc7bad_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasetpurchase',
            constraint=models.UniqueConstraint(fields=('buyer', 'dataset', 'order_item'), name='uniq_dataset_purchase_buyer_dataset_order_item'),
        ),
        migrations.AddConstraint(
            model_name='datasetpurchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('download_count', 0), ('last_downloaded_at__isnull', True)), ('download_count__gt', 0), _connector='OR'), name='chk_dataset_purchase_download_count_last_downloaded_consistency'),
        ),
    ]
