# Generated by Django 5.2.12 on 2026-04-21 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('law', 'Law'), ('finance', 'Finance'), ('news', 'News'), ('religion', 'Religion'), ('other', 'Other')], default='other', max_length=20)),
                ('subdomain', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='amharic', max_length=50)),
                ('data_type', models.CharField(choices=[('text', 'Text')], default='text', max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/raw/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.rawdocument')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/supporting/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='documents.rawdocument')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['user', 'status'], name='documents_r_user_id_09b9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['domain'], name='documents_r_domain_9b7cae_idx'),
        ),
    ]
