# Generated by Django 5.2.12 on 2026-04-21 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawdocument',
            name='documents_r_user_id_09b9e9_idx',
        ),
        migrations.RemoveField(
            model_name='rawdocument',
            name='status',
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='review_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['user'], name='documents_r_user_id_a68282_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['processing_status'], name='documents_r_process_2d7536_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['review_status'], name='documents_r_review__8682b7_idx'),
        ),
    ]
