# Generated by Django 6.0.4 on 2026-04-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_rawdocument_documents_r_user_id_09b9e9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Populated by the async metadata validator (e.g. Groq) with a human-readable reason.'),
        ),
    ]
