# Generated by Django 5.2.12 on 2026-05-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_replace_other_domain_with_general"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdocument",
            name="domain",
            field=models.CharField(
                choices=[
                    ("health", "Health"),
                    ("education", "Education"),
                    ("law", "Law"),
                    ("finance", "Finance"),
                    ("news", "News"),
                    ("religion", "Religion"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
