# Generated by Django 5.2.12 on 2026-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_migrate_news_to_politics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdocument",
            name="domain",
            field=models.CharField(
                choices=[
                    ("health", "Health"),
                    ("education", "Education"),
                    ("law", "Law"),
                    ("finance", "Finance"),
                    ("politics", "Politics"),
                    ("religion", "Religion"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
