# Generated by Django 5.2.12 on 2026-04-30 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0002_dataset_approved_at_dataset_approved_by_and_more"),
        ("marketplace", "0001_initial"),
        ("scoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("contributor", "Contributor"),
                            ("annotator", "Annotator"),
                            ("expert", "Expert"),
                            ("platform", "Platform"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("active", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("role", "-created_at"),
                "indexes": [
                    models.Index(fields=["role"], name="payments_co_role_e255c3_idx"),
                    models.Index(
                        fields=["active"], name="payments_co_active_95e7e1_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("commission_percentage__gte", 0),
                            ("commission_percentage__lte", 100),
                        ),
                        name="chk_commission_config_percentage_range",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("role",),
                        name="uniq_active_commission_config_per_role",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PayoutRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("minimum_points_required", models.PositiveIntegerField(default=0)),
                (
                    "minimum_withdrawal_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "score_to_currency_rate",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["active"], name="payments_pa_active_2f13e3_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("minimum_withdrawal_amount__gte", 0)),
                        name="chk_payout_rule_minimum_withdrawal_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score_to_currency_rate__gt", 0)),
                        name="chk_payout_rule_score_to_currency_rate_positive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("active",),
                        name="uniq_single_active_payout_rule",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "pending_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="ETB", max_length=8)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("bonus", "Bonus"),
                            ("commission", "Commission"),
                            ("withdrawal", "Withdrawal"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to="marketplace.order",
                    ),
                ),
                (
                    "related_scorelog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to="scoring.scorelog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("telebirr", "Telebirr"),
                            ("mobile_money", "Mobile Money"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payment_details", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_requests",
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at",),
            },
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["updated_at"], name="payments_wa_updated_b2cb6c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_balance__gte", 0)),
                name="chk_wallet_available_balance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("pending_balance__gte", 0)),
                name="chk_wallet_pending_balance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_earned__gte", 0)),
                name="chk_wallet_total_earned_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_withdrawn__gte", 0)),
                name="chk_wallet_total_withdrawn_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["transaction_type"], name="payments_pa_transac_55c76b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["status"], name="payments_pa_status_b6726a_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_a246c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["user", "created_at"], name="payments_pa_user_id_ccae69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["wallet", "created_at"], name="payments_pa_wallet__08d4a2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="chk_payment_transaction_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("processed_at__isnull", False), ("status", "completed")),
                    models.Q(("status", "completed"), _negated=True),
                    _connector="OR",
                ),
                name="chk_payment_transaction_completed_requires_processed_at",
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(fields=["status"], name="payments_wi_status_10ece7_idx"),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["requested_at"], name="payments_wi_request_bc4654_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["user", "status"], name="payments_wi_user_id_57a127_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="withdrawalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_withdrawal_request_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="withdrawalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("processed_at__isnull", False), ("status", "completed")),
                    models.Q(("status", "completed"), _negated=True),
                    _connector="OR",
                ),
                name="chk_withdrawal_request_completed_requires_processed_at",
            ),
        ),
    ]
