# Generated by Django 5.2.12 on 2026-05-19 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutrule",
            name="role",
            field=models.CharField(
                choices=[
                    ("contributor", "contributor"),
                    ("annotator", "annotator"),
                    ("expert", "expert reviewer"),
                    ("buyer", "buyer"),
                    ("admin", "admin"),
                    ("unknown", "unknown"),
                ],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
