# Generated by Django 5.2.13 on 2026-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payoutrule_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payoutrule",
            name="uniq_single_active_payout_rule",
        ),
        migrations.AddIndex(
            model_name="payoutrule",
            index=models.Index(fields=["role"], name="payments_pa_role_7af4c2_idx"),
        ),
        migrations.AddIndex(
            model_name="payoutrule",
            index=models.Index(
                fields=["role", "active"], name="payments_pa_role_831c29_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("role", "active"),
                name="uniq_active_payout_rule_per_role",
            ),
        ),
    ]
