# Generated by Django 5.2.13 on 2026-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_update_payout_rule_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
