# Generated by Django 5.2.12 on 2026-05-10 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0012_alter_annotationtask_domain_alter_experttask_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NLPAnnotationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('sentiment', 'Sentiment Analysis'), ('ner', 'Named Entity Recognition'), ('topic_classification', 'Topic Classification'), ('intent_detection', 'Intent Detection'), ('toxicity_classification', 'Toxicity Classification')], db_index=True, help_text='Which NLP task type this batch is for', max_length=50)),
                ('name', models.CharField(help_text='Human-readable name for this task batch', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task and annotation guidelines')),
                ('domain', models.CharField(blank=True, help_text='Domain scope (health, finance, law, etc.) for this task', max_length=50)),
                ('total_chunks', models.PositiveIntegerField(default=0, help_text='Total number of NLP chunks in this task')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this task is active for assignment')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nlp_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NLPChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('sentiment', 'Sentiment Analysis'), ('ner', 'Named Entity Recognition'), ('topic_classification', 'Topic Classification'), ('intent_detection', 'Intent Detection'), ('toxicity_classification', 'Toxicity Classification')], db_index=True, help_text='The NLP task this chunk is designated for', max_length=50)),
                ('text', models.TextField(help_text='The actual text content for NLP annotation')),
                ('order_index', models.PositiveIntegerField(help_text='Order of this NLP unit within the NLP chunks from source chunk')),
                ('char_start', models.PositiveIntegerField(help_text='Character offset start position in source chunk text')),
                ('char_end', models.PositiveIntegerField(help_text='Character offset end position in source chunk text')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible metadata storage for task-specific information')),
                ('generated_by_ai', models.BooleanField(default=False, help_text='Whether this chunk was AI-extracted or manually created')),
                ('ai_model_name', models.CharField(blank=True, help_text='Name of AI model used for extraction (if generated_by_ai=True)', max_length=255, null=True)),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='Confidence score of AI extraction (0-1 scale)', max_digits=5, null=True)),
                ('source_context', models.TextField(blank=True, help_text='Surrounding context from source chunk for annotation clarity')),
                ('source_domain', models.CharField(blank=True, help_text='Domain of source document (health, finance, law, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('pending_extraction', 'Pending Extraction'), ('ready_for_annotation', 'Ready for Annotation'), ('in_annotation', 'In Annotation'), ('consensus_ready', 'Consensus Ready'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_extraction', help_text='Lifecycle status of this NLP chunk', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this chunk is active for annotation')),
                ('requires_human_review', models.BooleanField(default=False, help_text='Whether this chunk needs human review (e.g., from AI extraction)')),
                ('source_chunk', models.ForeignKey(help_text='The QC-approved chunk this NLP unit was extracted from', on_delete=django.db.models.deletion.CASCADE, related_name='nlp_chunks', to='processing.chunk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NLPConsensus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('sentiment', 'Sentiment Analysis'), ('ner', 'Named Entity Recognition'), ('topic_classification', 'Topic Classification'), ('intent_detection', 'Intent Detection'), ('toxicity_classification', 'Toxicity Classification')], db_index=True, help_text='Type of NLP task (sentiment, NER, topic, etc.)', max_length=50)),
                ('final_labels', models.JSONField(help_text="Final consensus labels. Structure depends on task_type. Sentiment: {'sentiment': 'positive'}. NER: {'entities': [...]}. Topic: {'topic': 'finance'}.")),
                ('agreement_score', models.DecimalField(decimal_places=4, help_text='Agreement score among annotators (0-1 scale)', max_digits=5)),
                ('total_annotations', models.PositiveIntegerField(help_text='Number of annotations that contributed to this consensus')),
                ('requires_expert_review', models.BooleanField(default=False, help_text='Whether this consensus result needs expert review')),
                ('computed_at', models.DateTimeField(auto_now_add=True, help_text='When the consensus was computed')),
                ('nlp_chunk', models.OneToOneField(help_text="The NLP chunk being consensus'd", on_delete=django.db.models.deletion.CASCADE, related_name='consensus', to='nlp.nlpchunk')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='NLPTaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('declined', 'Declined')], db_index=True, default='assigned', help_text='Current status of this assignment', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the task was assigned')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the annotator started work on this task', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the annotator completed the task', null=True)),
                ('annotator', models.ForeignKey(help_text='The annotator assigned to this task', on_delete=django.db.models.deletion.CASCADE, related_name='nlp_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='The NLP task being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='nlp.nlpannotationtask')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='NLPAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('sentiment', 'Sentiment Analysis'), ('ner', 'Named Entity Recognition'), ('topic_classification', 'Topic Classification'), ('intent_detection', 'Intent Detection'), ('toxicity_classification', 'Toxicity Classification')], db_index=True, help_text='Type of NLP task (sentiment, NER, topic, etc.)', max_length=50)),
                ('labels', models.JSONField(help_text="Task-specific labels. Structure depends on task_type. Sentiment: {'sentiment': 'positive'}. NER: {'entities': [...]}. Topic: {'topic': 'finance'}.")),
                ('notes', models.TextField(blank=True, help_text='Annotator notes or reasoning for the label')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='Annotator confidence in this annotation (0-1)', max_digits=5, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, help_text='Seconds spent annotating this chunk', null=True)),
                ('is_skipped', models.BooleanField(default=False, help_text='Whether this chunk was skipped during annotation')),
                ('annotator', models.ForeignKey(help_text='The annotator who performed this annotation', on_delete=django.db.models.deletion.CASCADE, related_name='nlp_annotations', to=settings.AUTH_USER_MODEL)),
                ('nlp_chunk', models.ForeignKey(help_text='The NLP chunk being annotated', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='nlp.nlpchunk')),
                ('task_assignment', models.ForeignKey(help_text='The task assignment this annotation is part of', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='nlp.nlptaskassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NLPTaskChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(help_text='Order/position of this chunk within the task')),
                ('nlp_chunk', models.ForeignKey(help_text='The NLP chunk in this task', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='nlp.nlpchunk')),
                ('task', models.ForeignKey(help_text='The NLP annotation task', on_delete=django.db.models.deletion.CASCADE, related_name='task_chunks', to='nlp.nlpannotationtask')),
            ],
            options={
                'ordering': ['task', 'order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='nlpannotationtask',
            index=models.Index(fields=['task_type'], name='nlp_nlpanno_task_ty_64da87_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpannotationtask',
            index=models.Index(fields=['domain'], name='nlp_nlpanno_domain_5c269f_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpannotationtask',
            index=models.Index(fields=['-created_at'], name='nlp_nlpanno_created_5788d5_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpannotationtask',
            index=models.Index(fields=['is_active', 'task_type'], name='nlp_nlpanno_is_acti_94fcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpchunk',
            index=models.Index(fields=['source_chunk', 'task_type'], name='nlp_nlpchun_source__73235f_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpchunk',
            index=models.Index(fields=['task_type'], name='nlp_nlpchun_task_ty_e4083f_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpchunk',
            index=models.Index(fields=['status'], name='nlp_nlpchun_status_6b1ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpchunk',
            index=models.Index(fields=['source_chunk'], name='nlp_nlpchun_source__d5633f_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpchunk',
            index=models.Index(fields=['source_domain'], name='nlp_nlpchun_source__bcb41f_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpchunk',
            index=models.Index(fields=['-created_at'], name='nlp_nlpchun_created_94532f_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpchunk',
            index=models.Index(fields=['is_active', 'status'], name='nlp_nlpchun_is_acti_c70481_idx'),
        ),
        migrations.AddConstraint(
            model_name='nlpchunk',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gt', models.F('char_start'))), name='nlp_chunk_char_end_gt_start', violation_error_message='char_end must be greater than char_start'),
        ),
        migrations.AddConstraint(
            model_name='nlpchunk',
            constraint=models.CheckConstraint(condition=models.Q(('ai_confidence_score__isnull', True), models.Q(('ai_confidence_score__gte', 0), ('ai_confidence_score__lte', 1)), _connector='OR'), name='nlp_chunk_confidence_score_valid', violation_error_message='ai_confidence_score must be between 0 and 1 or NULL'),
        ),
        migrations.AddIndex(
            model_name='nlpconsensus',
            index=models.Index(fields=['task_type'], name='nlp_nlpcons_task_ty_06aed6_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpconsensus',
            index=models.Index(fields=['requires_expert_review'], name='nlp_nlpcons_require_9bcf77_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpconsensus',
            index=models.Index(fields=['-computed_at'], name='nlp_nlpcons_compute_0d84cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='nlpconsensus',
            constraint=models.CheckConstraint(condition=models.Q(('agreement_score__gte', 0), ('agreement_score__lte', 1)), name='nlp_consensus_agreement_score_valid', violation_error_message='agreement_score must be between 0 and 1'),
        ),
        migrations.AddConstraint(
            model_name='nlpconsensus',
            constraint=models.CheckConstraint(condition=models.Q(('total_annotations__gt', 0)), name='nlp_consensus_total_annotations_positive', violation_error_message='total_annotations must be greater than 0'),
        ),
        migrations.AddIndex(
            model_name='nlptaskassignment',
            index=models.Index(fields=['annotator'], name='nlp_nlptask_annotat_1f011f_idx'),
        ),
        migrations.AddIndex(
            model_name='nlptaskassignment',
            index=models.Index(fields=['task'], name='nlp_nlptask_task_id_bbd1db_idx'),
        ),
        migrations.AddIndex(
            model_name='nlptaskassignment',
            index=models.Index(fields=['status'], name='nlp_nlptask_status_ac0b96_idx'),
        ),
        migrations.AddIndex(
            model_name='nlptaskassignment',
            index=models.Index(fields=['annotator', 'status'], name='nlp_nlptask_annotat_979383_idx'),
        ),
        migrations.AddConstraint(
            model_name='nlptaskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'annotator'), name='uniq_nlp_assignment_task_annotator'),
        ),
        migrations.AddIndex(
            model_name='nlpannotation',
            index=models.Index(fields=['nlp_chunk'], name='nlp_nlpanno_nlp_chu_e2a1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpannotation',
            index=models.Index(fields=['annotator'], name='nlp_nlpanno_annotat_1264b5_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpannotation',
            index=models.Index(fields=['task_type'], name='nlp_nlpanno_task_ty_167e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpannotation',
            index=models.Index(fields=['nlp_chunk', 'annotator'], name='nlp_nlpanno_nlp_chu_a48287_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpannotation',
            index=models.Index(fields=['annotator', 'task_type'], name='nlp_nlpanno_annotat_b8c69a_idx'),
        ),
        migrations.AddConstraint(
            model_name='nlpannotation',
            constraint=models.UniqueConstraint(fields=('nlp_chunk', 'annotator'), name='uniq_nlp_annotation_chunk_annotator'),
        ),
        migrations.AddIndex(
            model_name='nlptaskchunk',
            index=models.Index(fields=['task', 'order_index'], name='nlp_nlptask_task_id_ffc86b_idx'),
        ),
        migrations.AddConstraint(
            model_name='nlptaskchunk',
            constraint=models.UniqueConstraint(fields=('task', 'nlp_chunk'), name='uniq_nlp_task_chunk_task_chunk'),
        ),
        migrations.AddConstraint(
            model_name='nlptaskchunk',
            constraint=models.UniqueConstraint(fields=('task', 'order_index'), name='uniq_nlp_task_chunk_order'),
        ),
    ]
