# Generated by Django 5.2.12 on 2026-04-24 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_remove_rawdocument_documents_r_user_id_09b9e9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('order_index', models.PositiveIntegerField()),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('token_count', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('extracted_document', 'order_index'),
            },
        ),
        migrations.CreateModel(
            name='AnnotationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('law', 'Law'), ('finance', 'Finance'), ('news', 'News'), ('religion', 'Religion'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotation_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIQualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_match', models.CharField(choices=[('match', 'Match'), ('not_match', 'Not Match'), ('uncertain', 'Uncertain')], max_length=20)),
                ('is_amharic', models.BooleanField()),
                ('readability', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('safety_label', models.CharField(choices=[('safe', 'Safe'), ('unsafe', 'Unsafe')], max_length=10)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('model_name', models.CharField(max_length=255)),
                ('model_version', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField()),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quality_check', to='processing.chunk')),
            ],
            options={
                'ordering': ('-processed_at',),
            },
        ),
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_domain_match', models.CharField(choices=[('match', 'Match'), ('not_match', 'Not Match'), ('uncertain', 'Uncertain')], max_length=20)),
                ('agreement_score', models.FloatField()),
                ('requires_expert_review', models.BooleanField(default=False)),
                ('total_annotations', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField()),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consensus', to='processing.chunk')),
            ],
            options={
                'ordering': ('-computed_at',),
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_match', models.CharField(choices=[('match', 'Match'), ('not_match', 'Not Match'), ('uncertain', 'Uncertain')], max_length=20)),
                ('is_amharic', models.BooleanField()),
                ('readability', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('safety_label', models.CharField(choices=[('safe', 'Safe'), ('unsafe', 'Unsafe')], max_length=10)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('resolution_reasoning', models.TextField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_reviews', to='processing.chunk')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExpertTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('law', 'Law'), ('finance', 'Finance'), ('news', 'News'), ('religion', 'Religion'), ('other', 'Other')], max_length=20)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['domain'], name='processing__domain_669d35_idx'), models.Index(fields=['created_at'], name='processing__created_0546e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpertTaskChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_task_links', to='processing.chunk')),
                ('expert_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_chunks', to='processing.experttask')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracted_text', models.TextField()),
                ('extraction_metadata', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField()),
                ('raw_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_document', to='documents.rawdocument')),
            ],
            options={
                'ordering': ('-processed_at',),
            },
        ),
        migrations.AddField(
            model_name='chunk',
            name='extracted_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='processing.extracteddocument'),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('declined', 'Declined')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='processing.annotationtask')),
            ],
            options={
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_match', models.CharField(choices=[('match', 'Match'), ('not_match', 'Not Match'), ('uncertain', 'Uncertain')], max_length=20)),
                ('is_amharic', models.BooleanField()),
                ('readability', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('safety_label', models.CharField(choices=[('safe', 'Safe'), ('unsafe', 'Unsafe')], max_length=10)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='processing.chunk')),
                ('task_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='processing.taskassignment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='processing.chunk')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_chunks', to='processing.annotationtask')),
            ],
            options={
                'ordering': ('task', 'order_index'),
            },
        ),
        migrations.AddIndex(
            model_name='annotationtask',
            index=models.Index(fields=['domain'], name='processing__domain_be9608_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationtask',
            index=models.Index(fields=['created_by'], name='processing__created_4dcca2_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationtask',
            index=models.Index(fields=['created_at'], name='processing__created_b5813c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiqualitycheck',
            index=models.Index(fields=['processed_at'], name='processing__process_3d1049_idx'),
        ),
        migrations.AddIndex(
            model_name='consensus',
            index=models.Index(fields=['requires_expert_review'], name='processing__require_f0e4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='consensus',
            index=models.Index(fields=['computed_at'], name='processing__compute_0f52b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='consensus',
            constraint=models.CheckConstraint(condition=models.Q(('agreement_score__gte', 0.0), ('agreement_score__lte', 1.0)), name='chk_consensus_agreement_score_range'),
        ),
        migrations.AddIndex(
            model_name='expertreview',
            index=models.Index(fields=['chunk'], name='processing__chunk_i_bedd44_idx'),
        ),
        migrations.AddIndex(
            model_name='expertreview',
            index=models.Index(fields=['expert'], name='processing__expert__05a00e_idx'),
        ),
        migrations.AddConstraint(
            model_name='expertreview',
            constraint=models.UniqueConstraint(fields=('chunk', 'expert'), name='uniq_expertreview_chunk_expert'),
        ),
        migrations.AddIndex(
            model_name='experttaskchunk',
            index=models.Index(fields=['expert_task'], name='processing__expert__c7d502_idx'),
        ),
        migrations.AddIndex(
            model_name='experttaskchunk',
            index=models.Index(fields=['chunk'], name='processing__chunk_i_98e1c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='experttaskchunk',
            constraint=models.UniqueConstraint(fields=('expert_task', 'chunk'), name='uniq_experttaskchunk_task_chunk'),
        ),
        migrations.AddIndex(
            model_name='extracteddocument',
            index=models.Index(fields=['processed_at'], name='processing__process_f0d4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['extracted_document'], name='processing__extract_695d40_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['order_index'], name='processing__order_i_cfd680_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['extracted_document', 'order_index'], name='processing__extract_8e8ec6_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('extracted_document', 'order_index'), name='uniq_chunk_extracted_document_order'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gt', models.F('char_start'))), name='chk_chunk_char_end_gt_start'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['status'], name='processing__status_d52719_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task'], name='processing__task_id_e251c5_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['annotator'], name='processing__annotat_db54e9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task', 'status'], name='processing__task_id_350373_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['annotator', 'status'], name='processing__annotat_200dcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'annotator'), name='uniq_taskassignment_task_annotator'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['chunk'], name='processing__chunk_i_66231c_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotator'], name='processing__annotat_806e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['task_assignment'], name='processing__task_as_6aa1af_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['chunk', 'annotator'], name='processing__chunk_i_352f23_idx'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('chunk', 'annotator'), name='uniq_annotation_chunk_annotator'),
        ),
        migrations.AddIndex(
            model_name='taskchunk',
            index=models.Index(fields=['task', 'order_index'], name='processing__task_id_60c088_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskchunk',
            constraint=models.UniqueConstraint(fields=('task', 'chunk'), name='uniq_taskchunk_task_chunk'),
        ),
        migrations.AddConstraint(
            model_name='taskchunk',
            constraint=models.UniqueConstraint(fields=('task', 'order_index'), name='uniq_taskchunk_task_order'),
        ),
    ]
