# Generated by Django 5.2.12 on 2026-04-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ai_processed', 'AI Processed'), ('in_annotation', 'In Annotation'), ('annotated', 'Annotated'), ('consensus_ready', 'Consensus Ready'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['status'], name='processing__status_3ccf51_idx'),
        ),
    ]
