# Generated by Django 5.2.12 on 2026-04-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0003_structured_extracteddocument"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="extracteddocument",
            new_name="processing__languag_902c20_idx",
            old_name="processing_langua_b8d7c6_idx",
        ),
        migrations.AlterField(
            model_name="extracteddocument",
            name="layout_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="extracteddocument",
            name="structure",
            field=models.JSONField(default=list),
        ),
    ]
