# Generated by Django on 2026-05-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0004_rename_processing_langua_b8d7c6_idx_processing__languag_902c20_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="quality_score",
            field=models.FloatField(default=0.0, db_index=True),
        ),
    ]
