# Generated by Django 6.0.4 on 2026-05-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_rename_processing_langua_b8d7c6_idx_processing__languag_902c20_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddocument',
            name='similarity_signature',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
