# Generated by Django 5.2.12 on 2026-05-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_add_chunk_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtask',
            name='extracted_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_tasks', to='processing.extracteddocument'),
        ),
    ]
