# Generated by Django 6.0.4 on 2026-05-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0005_extracteddocument_similarity_signature"),
        ("processing", "0006_annotationtask_extracted_document"),
    ]

    operations = []
