# Generated by Django 5.2.12 on 2026-05-03

from django.db import migrations, models


def forwards(apps, schema_editor):
    ExtractedDocument = apps.get_model("processing", "ExtractedDocument")

    ExtractedDocument.objects.filter(chunks__isnull=False).update(chunking_status="chunked")
    ExtractedDocument.objects.filter(chunks__isnull=True).update(chunking_status="pending")


def backwards(apps, schema_editor):
    ExtractedDocument = apps.get_model("processing", "ExtractedDocument")
    ExtractedDocument.objects.update(chunking_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0006_annotationtask_extracted_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracteddocument",
            name="chunking_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("chunked", "Chunked")],
                default="pending",
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]