# Generated by Django 5.2.12 on 2026-05-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0002_remove_rawdocument_documents_r_user_id_09b9e9_idx_and_more",
        ),
        ("processing", "0007_extracteddocument_chunking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="consensus",
            name="final_is_amharic",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consensus",
            name="final_readability",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="high",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consensus",
            name="final_safety_label",
            field=models.CharField(
                choices=[("safe", "Safe"), ("unsafe", "Unsafe")],
                default="safe",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="extracteddocument",
            index=models.Index(
                fields=["chunking_status"], name="processing__chunkin_8734fb_idx"
            ),
        ),
    ]
