# Generated by Django 5.2.12 on 2026-05-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_consensus_final_is_amharic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experttask',
            name='created_from_consensus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experttask',
            name='total_chunks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
