# Generated by Django 5.2.12 on 2026-05-03 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_experttask_created_from_consensus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertTaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('declined', 'Declined')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('expert_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_assignments', to='processing.experttask')),
            ],
            options={
                'ordering': ('-assigned_at',),
                'indexes': [models.Index(fields=['expert_task'], name='processing__expert__f6b25e_idx'), models.Index(fields=['expert'], name='processing__expert__de950c_idx'), models.Index(fields=['status'], name='processing__status_46153f_idx')],
                'constraints': [models.UniqueConstraint(fields=('expert_task',), name='one_expert_per_task'), models.UniqueConstraint(fields=('expert_task', 'expert'), name='uniq_experttaskassignment_task_expert')],
            },
        ),
    ]
