# Generated by Django 5.2.12 on 2026-05-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0010_experttaskassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracteddocument",
            name="similarity_signature",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
