# Generated by Django 5.2.12 on 2026-05-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0011_extracteddocument_similarity_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtask',
            name='domain',
            field=models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('law', 'Law'), ('finance', 'Finance'), ('news', 'News'), ('religion', 'Religion'), ('general', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='experttask',
            name='domain',
            field=models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('law', 'Law'), ('finance', 'Finance'), ('news', 'News'), ('religion', 'Religion'), ('general', 'General')], max_length=20),
        ),
    ]
