# Generated by Django 5.2.12 on 2026-05-24 22:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0012_alter_annotationtask_domain_alter_experttask_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiqualitycheck",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="aiqualitycheck",
            name="domain_match",
        ),
        migrations.RemoveField(
            model_name="aiqualitycheck",
            name="is_amharic",
        ),
        migrations.RemoveField(
            model_name="aiqualitycheck",
            name="readability",
        ),
        migrations.RemoveField(
            model_name="aiqualitycheck",
            name="safety_label",
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="domain_confidence",
            field=models.FloatField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="language_confidence",
            field=models.FloatField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="overall_confidence_score",
            field=models.FloatField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="predicted_domain",
            field=models.CharField(default="amharic", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="predicted_language",
            field=models.CharField(default="amhar", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="predicted_readability",
            field=models.CharField(default="sdfsa", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="raw_predictions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="readability_confidence",
            field=models.FloatField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="requires_manual_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aiqualitycheck",
            name="processed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="aiqualitycheck",
            index=models.Index(fields=["chunk"], name="processing__chunk_i_8ba9f3_idx"),
        ),
        migrations.AddIndex(
            model_name="aiqualitycheck",
            index=models.Index(
                fields=["requires_manual_review"], name="processing__require_325d09_idx"
            ),
        ),
    ]
