# Generated by Django 5.2.12 on 2026-05-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0013_remove_aiqualitycheck_confidence_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aiqualitycheck",
            name="processing__require_325d09_idx",
        ),
        migrations.RenameField(
            model_name="aiqualitycheck",
            old_name="raw_predictions",
            new_name="raw_qc_output",
        ),
        migrations.RenameField(
            model_name="aiqualitycheck",
            old_name="overall_confidence_score",
            new_name="safety_confidence",
        ),
        migrations.RemoveField(
            model_name="aiqualitycheck",
            name="requires_manual_review",
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="predicted_safety",
            field=models.CharField(default="safe", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aiqualitycheck",
            name="raw_safety_output",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ai_low_confidence", "AI Low Confidence"),
                    ("in_annotation", "In Annotation"),
                    ("annotated", "Annotated"),
                    ("consensus_ready", "Consensus Ready"),
                    ("escalated", "Escalated"),
                    ("resolved", "Resolved"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
