# Generated by Django 5.2.12 on 2026-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "processing",
            "0014_remove_aiqualitycheck_processing__require_325d09_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationtask",
            name="domain",
            field=models.CharField(
                choices=[
                    ("health", "Health"),
                    ("education", "Education"),
                    ("law", "Law"),
                    ("finance", "Finance"),
                    ("politics", "Politics"),
                    ("religion", "Religion"),
                    ("general", "General"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="domain",
            field=models.CharField(
                choices=[
                    ("health", "Health"),
                    ("education", "Education"),
                    ("law", "Law"),
                    ("finance", "Finance"),
                    ("politics", "Politics"),
                    ("religion", "Religion"),
                    ("general", "General"),
                ],
                max_length=20,
            ),
        ),
    ]
