# Generated by Django 5.2.12 on 2026-04-26 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_dataset_approved_at_dataset_approved_by_and_more'),
        ('marketplace', '0001_initial'),
        ('processing', '0002_chunk_status_chunk_processing__status_3ccf51_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('account_verified', 'Account Verified'), ('role_approved', 'Role Approved'), ('role_rejected', 'Role Rejected'), ('password_reset', 'Password Reset'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_reviewed', 'Task Reviewed'), ('adjudication_required', 'Adjudication Required'), ('dataset_purchased', 'Dataset Purchased'), ('dataset_sold', 'Dataset Sold'), ('payout_processed', 'Payout Processed'), ('withdrawal_update', 'Withdrawal Update'), ('maintenance', 'Maintenance'), ('security_alert', 'Security Alert'), ('feature_update', 'Feature Update')], max_length=50)),
                ('category', models.CharField(choices=[('system', 'System'), ('tasks', 'Tasks'), ('marketplace', 'Marketplace'), ('account', 'Account')], max_length=20)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('notification_type', '-created_at'),
                'indexes': [models.Index(fields=['notification_type'], name='notificatio_notific_d9e94e_idx'), models.Index(fields=['category'], name='notificatio_categor_7eadfe_idx'), models.Index(fields=['active'], name='notificatio_active_04ad4e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('notification_type',), name='uniq_active_notification_template_per_type')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('system', 'System'), ('tasks', 'Tasks'), ('marketplace', 'Marketplace'), ('account', 'Account')], max_length=20)),
                ('notification_type', models.CharField(choices=[('account_verified', 'Account Verified'), ('role_approved', 'Role Approved'), ('role_rejected', 'Role Rejected'), ('password_reset', 'Password Reset'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_reviewed', 'Task Reviewed'), ('adjudication_required', 'Adjudication Required'), ('dataset_purchased', 'Dataset Purchased'), ('dataset_sold', 'Dataset Sold'), ('payout_processed', 'Payout Processed'), ('withdrawal_update', 'Withdrawal Update'), ('maintenance', 'Maintenance'), ('security_alert', 'Security Alert'), ('feature_update', 'Feature Update')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('in_app_sent', models.BooleanField(default=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='datasets.dataset')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='marketplace.order')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='processing.annotationtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['category'], name='notificatio_categor_fd561f_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'), models.Index(fields=['user', 'category', 'created_at'], name='notificatio_user_id_4de3f0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_read', True), ('read_at__isnull', False)), models.Q(('is_read', False), ('read_at__isnull', True)), _connector='OR'), name='chk_notification_read_state_consistent')],
            },
        ),
    ]
